spring:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: ${DDL_AUTO:validate}
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
        platform: mysql
        url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/Socrates?serverTimezone=UTC}
        username: ${DATABASE_LOGIN:nextplus}
        password: ${DATABASE_PASSWORD:nextplus}
        driverClassName: com.mysql.cj.jdbc.Driver
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
